rotten_mangoes/config/routes.rb
Rails.application.routes.draw do
  root to: 'movies#index'
  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end

end

rotten_mangoes/app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews
  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: { only_integer: true}
  validates :description, presence: true
  validates :poster_image_url, presence: true
  validates :release_date, presence: true
  validate :release_date_is_in_the_future
  mount_uploader :image, ImageUploader
  scope :search_title, -> (term) {where("title like ?", term)}
  scope :search_director, -> (term) {where("director like ?", term)}
  scope :search_under_90, -> (term) {where("runtime_in_minutes < ?", term)}
  scope :search_bwt_90_120, -> {where("runtime_in_minutes > ? AND runtime_in_minutes < ?" , 90, 120)}
  scope :search_over_120, -> (term) {where("runtime_in_minutes > ?" , term)}


  def review_average
    if reviews.size > 0
    reviews.sum(:rating_out_of_ten)/reviews.size
    elsif !reviews.empty?
      reviews.rating_out_of_ten
    else
      "No reviews"
    end
  end

  def self.search(query)
    @movies = Movie.all
    @movies = @movies.search_title(query[:title]) if query[:title].present?
    @movies = @movies.search_director(query[:director]) if query[:director].present?
    if query[:duration].present? && query[:duration] == "90"
      @movies = @movies.search_under_90(query[:duration]) if query[:duration].present?
    elsif  query[:duration].present? && query[:duration] == "120"
      @movies = @movies.search_over_120(query[:duration]) if query[:duration].present?
    elsif  query[:duration].present? && query[:duration] == "100"
      @movies = @movies.search_bwt_90_120 if query[:duration].present?
    end
    return @movies
  end

  protected

  def release_date_is_in_the_future
    if release_date.present?
      errors.add(:release_date,"Should probably be in the future") if release_date < Date.today
    end
  end
end

rotten_mangoes/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
  validates :user, presence: true
  validates :movie, presence: true
  validates :text, presence: true
  validates :rating_out_of_ten, numericality: { only_integer: true}
  validates :rating_out_of_ten, numericality: { greater_than_or_equal_to: 1}
  validates :rating_out_of_ten, numericality: { less_than_or_equal_to: 10 }

  def self.user_reviews(id)
    Review.where(id)
  end
end

rotten_mangoes/app/models/user.rb
class User < ActiveRecord::Base
has_many :reviews, dependent: :destroy
has_secure_password

def full_name
  "#{firstname} #{lastname}"
end
end

rotten_mangoes/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_if_admin

  def index
    @users = User.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_admin_user_path, notice: "Added user, #{@user.firstname}"
    else
      render :page
    end
  end

  def show

  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.goodbye_email(@user).deliver_now
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def check_if_admin
    @user = User.find(session[:user_id]) if session[:user_id]
    unless @user.is_admin
      flash[:notice] = "You went to the wrong place so we sent you here!"
      redirect_to new_admin_user_path
    end
  end

  def user_params
    params.require(:user).permit(:email,:firstname, :lastname, :password, :password_confirmation, :is_admin)
  end

end

rotten_mangoes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  helper_method :current_user

end

rotten_mangoes/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if !params.empty?
      @movies = Movie.search(params)
      render :index
    else
      @movies = Movie.all
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
      if @movie.save
        redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
      else
        render :new
      end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movies_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url,:image, :description
      )
  end
end

rotten_mangoes/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :restrict_access
  before_filter :load_movie

  def new
    # @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.build
    #@review = Review.new(movie_id: @movie.id)
  end

  def create
      @movies = Movie.find(params[:movie_id])
      @review = @movies.reviews.build(review_params)
      @review.user_id = current_user.id

      if @review.save
        redirect_to @movie, notice: "Review created successfully"
      else
        render :new
      end
  end

  private

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

rotten_mangoes/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios"
  end
end

rotten_mangoes/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email,:firstname, :lastname, :password, :password_confirmation)
  end
end

rotten_mangoes/app/helpers/application_helper.rb
module ApplicationHelper
end

rotten_mangoes/app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d %Y")
  end
end

rotten_mangoes/app/helpers/sessions_helper.rb
module SessionsHelper
end

rotten_mangoes/app/helpers/users_helper.rb
module UsersHelper
end

rotten_mangoes/app/views/admin/users/index.html.erb
<small>
    <% if current_user %>
      <%if current_user.is_admin %>
      <% else %>
        <%= flash[:notice] = "You dont belong here" %>
        <% redirect_to movies_path %>
      <%end%>
    <% else %>
    <% end %>
</small>
<%= link_to "Add users", new_admin_user_path %>
<div>
  <%= paginate @users %>
</div>
<div>
  <h1>Users</h1>
  <% list = 0 %>
  <table class="striped" style="width:100%">
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>User Reviews</th>
    <th>Admin User</th>
    <th>Delete User</th>
  </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= link_to "user reviews", admin_user_path(user.id) %> </td>
        <td><%= user.is_admin %></td>
        <td><%= link_to "Delete", admin_user_path(user.id), :method => :delete, :data => {:confirm => "Are you sure?"} %> </td>
      </tr>
    <%end%>
  </table>
</div>

rotten_mangoes/app/views/admin/users/new.html.erb
 <h1>Add Users</h1>
    <%= form_for [:admin,@user] do |f| %>
      <% if @user.errors.any? %>
        <div>
          <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div>
        <%= f.label :firstname, "First Name" %><br>
        <%= f.text_field :firstname %>
      </div>
      <div>
        <%= f.label :lastname, "Last Name" %><br>
        <%= f.text_field :lastname %>
      </div>
      <div>
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
      </div>
      <div>
        <% f.label :is_admin, "check if admin" %><br>
        <%= f.check_box :is_admin %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>

rotten_mangoes/app/views/admin/users/show.html.erb
<% @review = Review.user_reviews(params[:id]) %>
<% if @review %>
  <% @review.each do |review| %>
    <p><%= review.text %></p>
    <%end%>
  <%else%>
    <p>no reviews found</p>
<%end%>

rotten_mangoes/app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
      <%if current_user.is_admin %>
        <%= link_to "Admin Management Panel", admin_users_path %>
      <%end%>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

rotten_mangoes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
</body>
</html>

rotten_mangoes/app/views/movies/_form.html.erb
     <%= form_for @movie, :html => {:multipart => true} do |f| %>
      <% if @movie.errors.any? %>
        <div>
          <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
          <ul>
            <% @movie.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div>
        <%= f.label :release_date %><br>
        <%= f.date_field :release_date %>
      </div>
      <div>
        <%= f.label :director %><br>
        <%= f.text_field :director %>
      </div>
      <div>
        <%= f.label :runtime_in_minutes %><br>
        <%= f.number_field :runtime_in_minutes %>
      </div>
      <div>
        <%= f.label :poster_image_url %><br>
        <%= f.text_field :poster_image_url %>
      </div>
      <div>
        <%= f.label "upload a image"%>
        <%= f.file_field :image %>
      </div>
      <div>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>
      <div>
        <%= f.submit "Submit" %>
      </div>
    <% end %>

rotten_mangoes/app/views/movies/_movie.html.erb
<%= link_to image_tag(movie.poster_image_url), movie_path(movie) %>
  <%= image_tag movie.image_url(:thumb).to_s %>
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <p> <%= movie.description %> </p>
  <hr>

rotten_mangoes/app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>
<%= link_to "Back to this movie", movie_path(@movie) %>

    <h2>Edit this movie.</h2>

    <%= render 'form' %>

rotten_mangoes/app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>
<%= link_to "Back to all movies", movies_path %><br/>

<%= form_tag movies_path, :method => 'get' do %>
  <%= text_field_tag :title, nil,placeholder: "title" %> <!-- text_field_tag :search, params[:search] -->
  <%= text_field_tag :director, nil, placeholder: "director" %>
  <%= label_tag(:duration, "Duration:") %>
<%= select_tag :duration, " <option value=''>Filter by Duration</option>
                            <option value='90'>Less than 90 minutes</option>
                            <option value='100'>90 to 120 minutes</option>
                            <option value='120'>More than 120 minutes</option>".html_safe, class: "browser-default"%>
 <%= submit_tag("Search") %>
<% end %>

<p><%= link_to "Submit a Movie", new_movie_path %></p>

<% @movies.each do |movie| %>
  <%= render :partial => "movie", :object => movie %>
<%end%>

rotten_mangoes/app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

rotten_mangoes/app/views/movies/show.html.erb
<h1>Movies#show</h1>
<p>Find me in app/views/movies/show.html.erb</p>

<hr>

<%= link_to "Back to all movies", movies_path %><br/>

<%= link_to image_tag(@movie.poster_image_url), movie_path(@movie) %>
<%= image_tag @movie.image_url(:thumb).to_s %>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
<h3>Average rating <%= @movie.review_average %></h3>
<h3><%= @movie.release_date %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= link_to "#{review.user.full_name}", user_path(review.user_id) %></small><br/>
  <% end %>
    <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
  <% else %>
    <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p>
<% end %>

rotten_mangoes/app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
<% if @review.errors.any? %>
<div>
  <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
  <ul>
    <% @review.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div>
  <%= f.label :text %><br>
  <%= f.text_area "text" %>
</div>
<div>
  <%= f.label :rating_out_of_ten %><br>
  <%= f.number_field :rating_out_of_ten %>
</div>
<div><%= f.submit "Submit" %></div>
<% end %>

rotten_mangoes/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

rotten_mangoes/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
 <h1>Sign Up</h1>
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div>
          <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div>
        <%= f.label :firstname, "First Name" %><br>
        <%= f.text_field :firstname %>
      </div>
      <div>
        <%= f.label :lastname, "Last Name" %><br>
        <%= f.text_field :lastname %>
      </div>
      <div>
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>

rotten_mangoes/app/views/users/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>
<h2>User profile for <%= @user.full_name %> </h2>
<h3>User email is <%= @user.email %></h3>
<h2>Review by <%= @user.full_name %></h2>
<% @reviews = Review.where(user_id: @user.id) %>
<% @reviews.each do |review| %>
  <% @movie = Movie.find(review.movie_id) %>
  <h3>Review for <%= @movie.title %></h2>
  <p><%= review.text %></p>
<% end %>